const tokyoSource='https://www.gotokyo.org/en/story/walks-and-tours/best-of-tokyo/index.html';
const places=[
{id:'narita',name:'Narita Airport · Terminal 1',city:'Tokyo',type:'flight',lat:35.7647,lng:140.3864,date:'26 Nov',meta:'Arrive 15:55 · NH816',text:'Outbound: 26 Nov, NH816 — Kuala Lumpur 08:05 (MYT) → Narita 15:55 (JST). Return: 9 Dec, NH815 — Narita 17:25 (JST) → Kuala Lumpur 00:15 (MYT) on 10 Dec. Terminal 1 at both airports according to your tickets; recheck before travel.',sourceLabel:'ANA e-ticket PDFs'},
{id:'taito',name:'Hotel Hitumugi Motoasakusa',city:'Tokyo',type:'hotel',lat:35.7085,lng:139.7844,date:'26 Nov',meta:'Check-in time unknown · Out 30 Nov, 10:00',text:'4-chōme-5-5 Motoasakusa, Taito City. Family Apartment 5. Checkout confirmed: 30 Nov at 10:00. Check-in date confirmed by you: 26 Nov. Check-in time still needs confirmation. Contact your host for check-in instructions. Pin shows the approximate address area.',sourceLabel:'taito.pdf · Airbnb booking'},
{id:'hilton',name:'Hilton Tokyo Bay',city:'Tokyo',type:'hotel',lat:35.6263,lng:139.8737,date:'30 Nov',meta:'In 15:00 · Out 2 Dec, 12:00',text:'1-8 Maihama, Urayasu, Chiba. 2 nights, 30 Nov–2 Dec. FAMILY HAPPY MAGIC PARK room for 2 adults + 1 child. Check-in 15:00; checkout 12:00. A convenient base for your Disney days; park tickets are not confirmed in the supplied files.',sourceLabel:'Hilton reservation confirmation'},
{id:'kyoto-home',name:'Lumen · Home in Kyoto',city:'Kyoto',type:'hotel',lat:35.0085,lng:135.7536,date:'2 Dec',meta:'Check-in time unknown · Out 6 Dec, 10:00',text:'176-6 Sanjōaburanokōjichō, Nakagyo-ku, Kyoto 604-8251 (京都市中京区三条油小路町176番地6). Checkout confirmed: 6 Dec at 10:00. Check-in date confirmed by you: 2 Dec. Check-in time still needs confirmation. Keypad entry; contact host Icy. The house is in a small alley: use the host’s exact Google Maps pin.',sourceLabel:'kyoto.pdf · Airbnb booking',directions:'https://maps.app.goo.gl/hFpzgA3FPnWw6QyQ7',image:'kyoto-home.jpg'},
{id:'hoshinoya',name:'HOSHINOYA Tokyo',city:'Tokyo',type:'hotel',lat:35.6878,lng:139.7653,date:'6 Dec',meta:'In 15:00 · Out 9 Dec, 12:00',text:'1-9-1 Otemachi, Chiyoda-ku. 3 nights, 6–9 Dec. Kiku Executive Triple for 2 adults + 1 child. Check-in 15:00; checkout 12:00. Seasonal dinner included on 6 December only; dinner time is not shown. Allow time for the Kyoto–Tokyo journey before check-in.',sourceLabel:'Hoshino Resorts confirmation'},
{id:'kul',name:'Kuala Lumpur Airport · Terminal 1',city:'Malaysia',type:'flight',lat:2.7456,lng:101.7072,date:'10 Dec',meta:'Arrive 00:15 · NH815',text:'NH816 departs Kuala Lumpur 26 Nov at 08:05. NH815 arrives 10 Dec at 00:15 — the day after leaving Japan. Both times are Malaysia time (UTC+8). Terminal 1 per your tickets.',sourceLabel:'ANA e-ticket PDFs'},
{id:'blue',name:'Blue Bottle · Kiyosumi Shirakawa',city:'Tokyo',type:'cafe',lat:35.6781,lng:139.7981,brief:'A coffee break in Tokyo’s café neighbourhood.',best:'Suggested: morning or afternoon',text:'Pair a coffee stop with a relaxed Kiyosumi Shirakawa neighbourhood walk. Suggested for one of your Tokyo city days; check the café’s current opening hours before setting off.',url:'https://store.bluebottlecoffee.jp/pages/kiyosumi'},
{id:'arabica',name:'% Arabica · Kyoto Higashiyama',city:'Kyoto',type:'cafe',lat:34.9984,lng:135.7784,brief:'Coffee among Higashiyama’s historic streets.',best:'Suggested: daytime',text:'An easy café stop to combine with the Higashiyama streets and Kiyomizu-dera area. This is a suggestion, with no reservation made. See the official location page for opening hours.',url:'https://arabica.com/location/arabica-kyoto-higashiyama/'},
{id:'ameyoko',name:'Ameyoko',city:'Tokyo',type:'market',lat:35.7098,lng:139.7745,brief:'Bustling stalls, shopping and casual food near Ueno.',best:'Suggested: afternoon / early evening',text:'A lively shopping street for browsing and snacks near your Taito stay. It is not a guaranteed late-night market; individual shops and restaurants keep different hours.',url:'https://www.gotokyo.org/en/destinations/northern-tokyo/ueno/index.html'},
{id:'hoppy',name:'Hoppy Street',city:'Tokyo',type:'market',lat:35.7138,lng:139.7938,brief:'Lanterns, old-fashioned eateries and evening energy.',best:'Suggested: early-evening stroll',text:'An evening food-street alternative to a night market, near Senso-ji. The street is izakaya-focused; with your child, choose a suitable restaurant and confirm seating and smoking arrangements before sitting down.',url:tokyoSource},
{id:'nishiki',name:'Nishiki Market',city:'Kyoto',type:'market',lat:35.0050,lng:135.7649,brief:'Kyoto flavours along a covered food-shopping street.',best:'Suggested: lunch / afternoon',text:'Plan this as a daytime market visit. Individual shops have different opening days and hours; many close on Wednesdays. Eat purchases at the shop or inside rather than while walking.',url:'https://www.kyoto-nishiki.or.jp/en/contact/'},
{id:'pontocho',name:'Pontocho',city:'Kyoto',type:'market',lat:35.0062,lng:135.7715,brief:'An atmospheric lane for a Kyoto dinner wander.',best:'Suggested: evening',text:'A dining district for an evening stroll and dinner, rather than a stall-based night market. Choose a family-friendly restaurant and check reservations or seating requirements directly.',url:'https://kyoto.travel/en/areas/central/'},
{id:'sensoji',name:'Senso-ji & Nakamise',city:'Tokyo',type:'visit',lat:35.7148,lng:139.7967,brief:'Temple grounds, traditional snacks and little shops.',best:'Suggested: morning',text:'A natural sightseeing choice near your Taito base. Explore the temple complex and Nakamise shopping street, then continue toward Hoppy Street if you want an evening meal. Shop hours vary.',url:tokyoSource},
{id:'disneyland',name:'Tokyo Disneyland',city:'Tokyo',type:'visit',lat:35.6329,lng:139.8804,brief:'A full park day near Hilton Tokyo Bay.',best:'Suggested: during 30 Nov–2 Dec stay',text:'Choose a dated park ticket and check the official calendar. Your hotel reservation does not establish a park reservation. No park tickets were found in your project files.',url:'https://www.tokyodisneyresort.co.jp/en/tdr/facility'},
{id:'disneysea',name:'Tokyo DisneySea',city:'Tokyo',type:'visit',lat:35.6267,lng:139.8851,brief:'A second Disney option beside your resort base.',best:'Suggested: during 30 Nov–2 Dec stay',text:'An alternative or second park day around your Hilton stay. Check dated ticket availability and park hours on the official site; no attraction or park booking is implied.',url:'https://www.tokyodisneyresort.co.jp/en/tds/'},
{id:'kiyomizu',name:'Kiyomizu-dera & Higashiyama',city:'Kyoto',type:'visit',lat:34.9949,lng:135.7850,brief:'Temple views and Kyoto’s historic lanes.',best:'Suggested: morning / daytime',text:'Combine the temple area with % Arabica and a walk through Higashiyama. Check the temple’s current opening information; no special autumn illumination dates have been assumed.',url:'https://kyoto.travel/en/areas/gion-kiyomizu/'}
];
const types={hotel:['■','Stay','#294f75'],flight:['✈','Flight','#476477'],cafe:['●','Café','#985227'],market:['◆','Market / evening','#af3971'],visit:['▲','Explore','#287866']};
let region='Tokyo',selected='narita',map,markers={};
const byId=id=>places.find(p=>p.id===id);
const directions=p=>p.directions||'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.type==='hotel'?p.name+' '+p.text.split('.')[0]:p.name+' '+p.city);
const link=(url,label)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
function selectPlace(id,fly=true){selected=id;const p=byId(id);document.querySelector('#detail').innerHTML=`<div class="detail-box">${p.image?`<img src="${p.image}" alt="Courtyard bath at your Kyoto home">`:''}<span class="eyebrow">${types[p.type][1]} · ${p.city}</span><h2>${p.name}</h2><p>${p.text}</p><p>${p.sourceLabel?'Source: '+p.sourceLabel:'Suggested visit · Not booked'}</p><div class="links">${link(directions(p),'Directions')}${p.url?link(p.url,'Venue information'):''}</div></div>`;document.querySelectorAll('[data-id]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.id===id));if(map&&fly){map.flyTo([p.lat,p.lng],p.type==='flight'?10:15,{duration:.6});markers[id]?.openPopup();}}
function renderPlaces(){const show=places.filter(p=>!['hotel','flight'].includes(p.type)&&(region==='All'||p.city===region));document.querySelector('#places').innerHTML=show.map(p=>`<button class="place" data-id="${p.id}" aria-pressed="${selected===p.id}"><small class="${p.type}">${types[p.type][0]} ${types[p.type][1]} · ${p.city}</small><strong>${p.name}</strong><p>${p.brief}</p><span class="best">${p.best}</span></button>`).join('');document.querySelectorAll('.place').forEach(b=>b.onclick=()=>{selectPlace(b.dataset.id);document.querySelector('.map-side').scrollIntoView({behavior:'smooth',block:'start'});});document.querySelector('#count').textContent=places.filter(p=>region==='All'||p.city===region).length+' places';}
const journey=[['narita','26 Nov','Arrive in Japan','15:55 · Narita · NH816'],['taito','26 Nov','Taito stay','Check-in time unknown · Out 30 Nov, 10:00'],['hilton','30 Nov','Hilton Tokyo Bay','Check-in 15:00 · Out 2 Dec, 12:00'],['kyoto-home','2 Dec','Kyoto home','Check-in time unknown · Out 6 Dec, 10:00'],['hoshinoya','6 Dec','HOSHINOYA Tokyo','Check-in 15:00 · Out 9 Dec, 12:00'],['narita','9 Dec','Fly home · NH815','Narita 17:25 → KUL 10 Dec, 00:15']];
document.querySelector('#journey').innerHTML=journey.map(([id,date,title,meta])=>`<button class="stop" data-id="${id}" aria-pressed="false"><span class="stop-date">${date}</span><span><span class="stop-name">${title}</span><span class="stop-meta">${meta}</span></span></button>`).join('');
document.querySelectorAll('.stop').forEach(b=>b.onclick=()=>{const p=byId(b.dataset.id);setRegion(p.city==='Malaysia'?'All':p.city,false);selectPlace(p.id);if(innerWidth<760)document.querySelector('.map-side').scrollIntoView({behavior:'smooth'});});
function setRegion(value,fit=true){region=value;document.querySelectorAll('[data-region]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.region===region));renderPlaces();if(map){for(const p of places){if(region==='All'||p.city===region)markers[p.id].addTo(map);else map.removeLayer(markers[p.id]);}if(fit){const points=places.filter(p=>region==='All'||p.city===region).map(p=>[p.lat,p.lng]);map.fitBounds(points,{padding:[35,35],maxZoom:13});}}}
document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>setRegion(b.dataset.region));
renderPlaces();selectPlace('narita',false);
if(window.L){document.querySelector('#map-loading').remove();map=L.map('map',{scrollWheelZoom:false}).setView([35.697,139.80],12);let tilesLoaded=false;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);tiles.on('tileload',()=>{tilesLoaded=true;});tiles.on('tileerror',()=>{if(!tilesLoaded)document.querySelector('.map-note').textContent='Map tiles are unavailable. Place details and Directions links still work. Pins show approximate locations.';});for(const p of places){const [symbol,,color]=types[p.type];markers[p.id]=L.marker([p.lat,p.lng],{title:p.name,alt:p.name,icon:L.divIcon({className:'',html:`<span class="pin" style="--pin:${color}">${symbol}</span>`,iconSize:[32,32],iconAnchor:[16,16]})}).bindPopup(`<strong>${p.name}</strong><br>${p.meta||p.best||''}<br>${link(directions(p),'Directions')}`).on('click',()=>selectPlace(p.id,false));}setRegion('Tokyo');}else{document.querySelector('#map-loading').innerHTML='The map could not load. You can still select any booking or place and use its Directions link.';}
